# Generated by Django 4.1.3 on 2022-11-26 15:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='owner',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='name',
            new_name='title',
        ),
        migrations.AlterUniqueTogether(
            name='news',
            unique_together={('code',)},
        ),
        migrations.AddField(
            model_name='news',
            name='subtitle',
            field=models.CharField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='news',
            name='description',
            field=models.TextField(blank=True, default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
    ]
