# Generated by Django 4.1.3 on 2022-11-26 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_news_new'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='description',
            field=models.TextField(blank=True, max_length=980),
        ),
        migrations.AlterField(
            model_name='new',
            name='subtitle',
            field=models.CharField(max_length=280),
        ),
        migrations.AlterField(
            model_name='new',
            name='title',
            field=models.CharField(max_length=140),
        ),
    ]
