# Generated by Django 4.1.3 on 2022-11-26 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_new_description_alter_new_subtitle_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='new',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='new',
            name='code',
        ),
    ]
