# Generated by Django 4.1.3 on 2022-11-28 23:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0008_rename_author_id_new_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Imagen de portada'),
        ),
        migrations.AlterField(
            model_name='new',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='new',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creación'),
        ),
        migrations.AlterField(
            model_name='new',
            name='description',
            field=models.TextField(blank=True, max_length=980, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='new',
            name='subtitle',
            field=models.CharField(max_length=280, verbose_name='Subtítulo'),
        ),
        migrations.AlterField(
            model_name='new',
            name='title',
            field=models.CharField(max_length=140, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='new',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Última modificación'),
        ),
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='avatar')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
